#!/bin/bash
jupyter nbextension enable --py widgetsnbextension
jupyter labextension install @jupyter-widgets/jupyterlab-manager \
                             @jupyter-widgets/jupyterlab-manager plotlywidget \
                             @jupyterlab/toc \
                             jupyterlab-plotly

#EOF
